### ISSUE TITLE
Node vs instance?

### ISSUE THREAD

**Issue by pdf** [prometheus/consul_exporter#10]
It seems like it would be more sensible to expose the service node as the `instance` label, rather than `node`?  That would make it much easier to combine with other instance-based queries or dashboards.

It might be suggested that this could be done with relabelling, but that doesn't appear to be possible, if you're also doing service discovery (via consul obviously).  Since you generally want to relabel generically across all discovered services, there's probably an enhancement request for prometheus proper to be made to address relabelling specific discovered targets, but just having this exporter send node as instance would solve my use-case.

Would a PR be accepted?

**Comment by brian-brazil** [comment]
I think what you're looking for here is some form of relabel operator in prometheus itself.

**Comment by pdf** [comment]
I went looking for an issue in prometheus that might reference this desire, and found the `metric_relabel_configs` option, which looks like it will do the work (I brushed over this reading the docs because it's not clearly documented).  Using it with SD does mean doing some funky regex dances to match jobs and values, but it'll work.  Sorry for the noise.
