### ISSUE TITLE
multiarch docker images

### ISSUE THREAD

**Issue by ncabatoff** [prometheus/consul_exporter#103]
Now that https://github.com/prometheus/promu/issues/89 has landed, can we get the same here as was done for node_exporter and prometheus please?

**Comment by simonpasquier** [comment]
With https://github.com/prometheus/consul_exporter/pull/119 and #121 merged, we have `arm64` and `armv7` variants for container images. I'm closing it for now, feel free to reopen if it doesn't match your expectations.
