### ISSUE TITLE
The default timeout is too small?

### ISSUE THREAD

**Issue by gouthamve** [prometheus/consul_exporter#106]
The default timeout for `consul_exporter` on HTTP reqs to consul is `200ms`, that seems a tad too small. We have a single node consul cluster running and sometimes the `/status/peers` takes `~400ms` to respond.

How do you folks feel about raising the default timeout? Or are we doing something wrong in our setup and this is not an issue that everyone faces?

**Comment by grobie** [comment]
We're not experiencing any issues with that timeout in any of our clusters. I did a quick test and haven't gotten anything slower than a 15ms for that particular endpoint. Regardless, I don't think it would hurt to raise the default timeout.

**Comment by Kerl1310** [comment]
I'm happy to pick this up
