### ISSUE TITLE
Alert when service is not running and is not in maintenace mode 

### ISSUE THREAD

**Issue by rsridivya** [prometheus/consul_exporter#113]
I have a situation where I have to send an alert to alertmanger when the service is not running and the maintenance mode is not enabled in consul for that service.
I tried to use query expression like below:
```
consul_health_service_status{check!~"_service_maintenance.*",status="critical",job="XXXX"}  == 1 and consul_health_service_status{check=~"_service_maintenance.*",job="XXXX"} != 1
```

Above query expression doesn't send an alert when the first condition (which means it fails TCP check ) and maintenance mode is enabled. 
But it is failing to send an alert when the TCP check fails and maintenance mode is not enabled for that service. This is beacuse executing 
`consul_health_service_status{check=~"_service_maintenance.*",job="XXXX"}` doesn't return any value when the maintenance mode is not enabled.

Can  you please help me how do I have to refine my alert expression in prometheus rule.

**Comment by simonpasquier** [comment]
This should work:

```
(
  (consul_health_service_status{check!~"_service_maintenance.*",status="critical",job="XXXX"}  == 1)
  *
  (consul_health_service_status{check=~"_service_maintenance.*",job="XXXX"} != bool 1)
) == 1
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
