### ISSUE TITLE
consul-exporter is not exposing full metrics

### ISSUE THREAD

**Issue by Kartik-28** [prometheus/consul_exporter#129]
I am using consul_exporter docker image and i am getting the metrics. However, i noticed i am not getting the following data at the endpoint. Furthermore, consul_up gives 0.

consul_raft_peers 
consul_serf_lan_members
consul_catalog_services 
consul_catalog_service_node_healthy 
consul_health_node_status
consul_health_service_status 

**I am using this command to run docker image :**
docker run --name consul-exporter --restart=unless-stopped -p 9107:9107 prom/consul-exporter --consul.server=172.17.0.1:8500

Is there any config I have to do on the consul side ?

**Comment by simonpasquier** [comment]
If `consul_up` is 0 then the exporter fails to query the Consul server for some reason. Have you checked the logs of the exporter?

**Comment by simonpasquier** [comment]
Feel free to reopen with more details.

**Comment by hanumank8** [comment]
Same issue exist for us, Can you let us know to get all the metrics?
