### ISSUE TITLE
consul.server parameter should accept multiple server addresses

### ISSUE THREAD

**Issue by thachmai** [prometheus/consul_exporter#13]
In a production environment, consul is likely to be run as a cluster. It'd be great if the consul.server param accepts multiple server addresses to make it more robust during partitioning.

**Comment by ewr** [comment]
The intention generally is that you're running one exporter per server, so each exporter has a view of its local server. You want the exporter as close to its monitoring target as possible.

**Comment by thachmai** [comment]
OK thanks for the info.

Does this take care of the case when partition occurs between nodes? For example, we have a cluster of 3 nodes: c1, c2, c3 (c1 is leader). c3 cannot join the cluster due to network/latency/etc issue. If I run 3 exporters each on c1, c2, c3, will they report conflicting info to prometheus?

**Comment by grobie** [comment]
Yes, but including an instance label. This allows you to have all information available which partition saw what kind of information.
