### ISSUE TITLE
Add /health endpoint returning 200 OK

### ISSUE THREAD

**Issue by analytically** [prometheus/consul_exporter#150]
For schedulers like Nomad and K8s it's handy to have a simple /health endpoint returning 200 OK indicating service availability.

**Comment by analytically** [comment]
Currently it looks a little ugly when using / as health check:

![image](https://user-images.githubusercontent.com/254434/68818909-6674f700-063b-11ea-9fd6-d78c0b1d3e0e.png)

**Comment by simonpasquier** [comment]
Do you want to submit a PR for this?
