### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by karuppiah7890** [prometheus/consul_exporter#154]
The current stable version `v0.5.0` . Looks like there have been a lot of commits after that, is it possible to release a new version?

**Comment by simonpasquier** [comment]
It's on my to-do list, hopefully it will happen before the end of next week.

**Comment by karuppiah7890** [comment]
Thanks a lot! :D

**Comment by simonpasquier** [comment]
This is available: https://github.com/prometheus/consul_exporter/releases/tag/v0.6.0

**Comment by karuppiah7890** [comment]
Thanks a lot! 😄 🙏
