### ISSUE TITLE
Is this compatible with consul 0.6+?

### ISSUE THREAD

**Issue by mledoze** [prometheus/consul_exporter#16]
Hello, 

I have a consul agent (v0.6.3) installed on my host and I'm trying to make the exporter work in a docker container, but I have the following error: `level=error msg="Query error is Get http://172.17.42.1:8500/v1/status/peers: dial tcp 172.17.42.1:8500: getsockopt: connection refused" file="consul_exporter.go" line=150`

```bash
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64
```

```bash
# consul version
Consul v0.6.3
Consul Protocol: 3 (Understands back to: 1)
```

```bash
# consul info
agent:
        check_monitors = 0
        check_ttls = 0
        checks = 1
        services = 1
build:
        prerelease =
        revision = c933efde
        version = 0.6.3
consul:
        known_servers = 3
        server = false
runtime:
        arch = amd64
        cpu_count = 2
        goroutines = 70
        max_procs = 2
        os = linux
        version = go1.5.3
serf_lan:
        encrypted = false
        event_queue = 0
        event_time = 4
        failed = 0
        intent_queue = 0
        left = 0
        member_time = 324
        members = 22
        query_queue = 0
        query_time = 1
```
Thank you for your help.

**Comment by ewr** [comment]
I'm not a Docker person, but I'd suspect the issue is just about reaching the Consul port, not with a Consul version. You might want to check which IP Consul is binding to, and make sure that Docker is routing your container networking correctly.

**Comment by sdurrheimer** [comment]
With the docker 1.9.1 vestion, the IP of the docker host is '172.17.0.1' and not '172.17.42.1'.

**Comment by mledoze** [comment]
@sdurrheimer it does not work with `172.17.0.1`. 

I have this in my iptables:
```bash
# iptables -L
...
Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:9107
...
```

**Comment by sdurrheimer** [comment]
@mledoze Can you give us the launch commands and options used of those containers ?

**Comment by mledoze** [comment]
@sdurrheimer sure, here is the container run command: 

```bash
docker run -d --restart=always \
    -p 9107:9107 \
    --name prometheus-consul-bridge \
    prom/consul-exporter -consul.server=172.17.42.1:8500
```

Consul is launched on the host machine with this command: 
```bash
/bin/consul agent -config-dir /etc/consul -advertise=<private_ipv4>
```

**Comment by sdurrheimer** [comment]
@mledoze By default, Consul client interfaces are binded to `127.0.0.1`, so the HTTP interface is not accessible via `172.17.42.1:8500`.
You can use the `-client` option to change the address. In you case, you can use 172.17.0.1 (docker host bridge IP) or your private IPv4. 
https://www.consul.io/docs/agent/options.html#_client for more informations.

**Comment by mledoze** [comment]
@sdurrheimer it works now when I run the consul agent with `-client=172.17.42.1`. However on the host, I must now do `consul members -rpc-addr=172.17.42.1:8400` to access consul members, which is normal.
Thank you for your help!
