### ISSUE TITLE
Grabbing consul info without hard coding

### ISSUE THREAD

**Issue by nursejason** [prometheus/consul_exporter#17]
Maybe I'm missing some awesome command in the Docker universe, but I want to use the exporter without having to hard code the IP address to Consul. I want to link to another container and have it work, or specify a variable to have exporter go and find the hosts IP manually, so that it can then get to Consul. Is there a command I'm missing that could do this for me? Or am I stuck hard coding the `docker0` IP of the host I'm on in order to access Consul?

**Comment by NoumanSaleem** [comment]
Sure, you can link the consul container when running consul_exporter
`docker run --link consul prom/consul-exporter -consul.server=consul:8500`
