### ISSUE TITLE
consul_serf_lan_member_status failed in exposing.

### ISSUE THREAD

**Issue by shivani-hotstar** [prometheus/consul_exporter#174]
Deployed consul-exporter on k8s cluster .

Helm 
NAME                             	CHART VERSION	APP VERSION	DESCRIPTION
stable/prometheus-consul-exporter	0.1.4        	0.4.0      	A Helm chart for the Prometheus Consul Exporter

All metrics are exposed successfully except **consul_serf_lan_member_status**

I guess this metrics is recently been added and failing in exposing with all other metrics.

**Comment by shivani-hotstar** [comment]
Any update on this ?

**Comment by simonpasquier** [comment]
which version of the exporter do you run? can you share logs?

**Comment by shivani-hotstar** [comment]
Version
image: prom/consul-exporter:v0.4.0

Logs of consul-exporter pod .
`time="2020-06-23T17:35:19Z" level=info msg="Starting consul_exporter (version=0.4.0, branch=HEAD, revision=75f02d80bbe2191cd0af297bbf200a81cbe7aeb0)" source="consul_exporter.go:373"
time="2020-06-23T17:35:19Z" level=info msg="Build context (go=go1.10.3, user=root@7ff1893a5a5d, date=20180810-10:51:25)" source="consul_exporter.go:374"
time="2020-06-23T17:35:19Z" level=info msg="Listening on :9107" source="consul_exporter.go:403"`

**Comment by simonpasquier** [comment]
The metric has been added in v0.6.0 by https://github.com/prometheus/consul_exporter/commit/6a90bd50bd5233d81f355807fba87d9ef4edabf4. You need to upgrade to a newer version.
