### ISSUE TITLE
error "was collected before with the same name and label values"

### ISSUE THREAD

**Issue by infa-mlagad** [prometheus/consul_exporter#186]
I have deployed consul exporter for consul monitoring in with prometheus. 

Expected to see consul exporter metrics in prometheus.

Consul exporter gets running but shows error as below
error gathering metrics:36 error(s) occurred:\n* collected metric \"consul_catalog_service_node_healthy\" { label:<name:\"node\" value:\"xxxx\" > label:<name:\"service_id\" value:\"xxxx\" > label:<name:\"service_name\" value:\"xxx\" > gauge:<value:1 > } was collected before with the same name and label values

This deployment is done on EKS. 

* System information:
kubernetes version - 1.14

* consul_exporter version:
consul exporter version - 0.7.1

* Consul version:
consul version- v1.4.0

* Prometheus version:
prometheus verssion - 2.15.2"

* Logs:
```
level=info ts=2020-09-10T08:01:43.519Z caller=consul_exporter.go:486 msg="Starting consul_exporter" version="(version=0.7.1, branch=HEAD, revision=ae46e2ea980ecf1c961bf332b71160be707b5e98)"
level=info ts=2020-09-10T08:01:43.520Z caller=consul_exporter.go:487 build_context="(go=go1.14.6, user=root@fdd571c00696, date=20200721-15:34:41)"
level=info ts=2020-09-10T08:01:43.520Z caller=consul_exporter.go:538 msg="Listening on address" address=:9107
error gathering metrics:36 error(s) occurred:\n* collected metric \"consul_catalog_service_node_healthy\" { label:<name:\"node\" value:\"xxxx\" > label:<name:\"service_id\" value:\"xxxx\" > label:<name:\"service_name\" value:\"xxx\" > gauge:<value:1 > } was collected before with the same name and label values

```

There are no duplicate services registered in my consuls. I tried deleting the chart with purge and reinstalling. still same error. 
```
   spec:
      containers:
      - args:
        - --consul.server=xxxx
        command:
        - consul_exporter
        image: prom/consul-exporter:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: prometheus-consul-exporter
        ports:
        - containerPort: 9107
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
```

**Comment by simonpasquier** [comment]
What do you get from the Consul when requesting `/v1/health/service/xxx` (where `xxx` is replaced by the name of the service in Consul)?

**Comment by infa-mlagad** [comment]
It gives me a descriptive page for that service. copied top few lines below.


Node |  
-- | --
ID | "07442016-4c86-bb8c-9010-4d8921d9428d"
Node | "xxxxx
Address | "xxxx"
Datacenter | "xxxx"
TaggedAddresses |  
lan | "xxx"
wan | "xx"
Meta |  
consul-network-segment | ""
CreateIndex | 96681827
ModifyIndex | 96690539
Service |  
ID | "xxxx"
Service | "xxxxx"

Please let me know if you are looking for anything specific from this page.

**Comment by simonpasquier** [comment]
> Please let me know if you are looking for anything specific from this page.

I'd like the full JSON output.

**Comment by infa-mlagad** [comment]
found that there was duplicate data for that service. After removing the duplicates this solved. Thanks a lot for stopping by.
