### ISSUE TITLE
New Release/Tag

### ISSUE THREAD

**Issue by cretz** [prometheus/consul_exporter#21]
There hasn't been a release in almost a year. Ref: https://groups.google.com/forum/?fromgroups#!topic/prometheus-developers/I2eNTRqA48o.

**Comment by Djidiouf** [comment]
@sdurrheimer Is another consul_exporter release planned anytime soon?

I tried to build the consul_exporter from sources but I'm not at ease with go configuration and my attempts have failed (just doing a make doesn't work).

**Comment by grobie** [comment]
I created a v0.3.0 milestone and will try to release it next week.

**Comment by rkrzr** [comment]
Hey is this still WIP? We would prefer to build against a stable tag instead of master, so a new release would be much appreciated.

**Comment by grobie** [comment]
Acknowledged. I'm traveling a lot right now, but plan to release a new
version this year.

**Comment by grobie** [comment]
Done! https://github.com/prometheus/consul_exporter/releases/tag/v0.3.0
