### ISSUE TITLE
TLS Server Support

### ISSUE THREAD

**Issue by mzbenami** [prometheus/consul_exporter#23]
Is my understanding of the code correct that the exporter server side can't listen with TLS?

If not, would you mind if I submitted a PR to enable it with environment variables?

**Comment by brian-brazil** [comment]
No Prometheus component does auth or security on the server side. There's just too many options and possibilities (TLS alone has 13 for example) for us to sanely support.

We recommend using a reverse proxy such as nginx.

**Comment by grobie** [comment]
You can read more about the reasoning why Prometheus components don't provide any kind of authorization here: http://www.robustperception.io/prometheus-security-authentication-authorization-and-encryption/

**Comment by soumyadipDe** [comment]
Hi,
There is a code for consul server with TLS encryption in api.go named TLSConfig. I did not find any documentation on how to pass CAFile, CertFile, KeyFile in that. I am using consul_exporter docker image. Any help on this?

Thanks!

**Comment by grobie** [comment]
This issue was about adding server TLS support so that connection from Prometheus when scraping metrics would be secured. We decided to not support that use case directly in exporters as Brian said.

I created #32 for client TLS support.
