### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by deepthawtz** [prometheus/consul_exporter#27]
I'd like to be able to connect to a `-consul.server` over https. Doesn't seem possible

**Comment by deepthawtz** [comment]
if this is desirable I'd be happy to discuss implementation and contribute a patch.

perhaps an `-ssl` option to enable HTTPS

for me this would be great because I've disabled non-HTTPS access on my consul cluster

**Comment by grobie** [comment]
This sounds good and we should add it. I would try not to have an extra flag for that, passing in a URL with a https:// scheme should be enough.

Do you use a valid certificate which can be publicly verified?

**Comment by deepthawtz** [comment]
In my case I do use a publicly verified cert but.. might be nice to allow a skip verify option for those that don't. `envconsul` and `vault` both provide a flag to skip cert verification if that is desired

**Comment by deepthawtz** [comment]
I could implement https:// scheme recognition and we could discuss on a PR from there

**Comment by grobie** [comment]
:+1:

**Comment by brian-brazil** [comment]
Do we need the full client auth options from Prometheus?

**Comment by grobie** [comment]
Maybe. Consul API either allows scheme and host to be set, or to pass in an own HTTP client https://github.com/hashicorp/consul/blob/master/api/api.go#L104-L128. We might get away with just setting the two basic attributes for now.
