### ISSUE TITLE
additional metrics

### ISSUE THREAD

**Issue by EvertMDC** [prometheus/consul_exporter#29]
Hello,

Would there be a possibility to add the following metrics to the exported data?

consul.consul.leader.reconcile.count
consul.serf.events.consul_new_leader

It's based on [this article](https://engineering.datadoghq.com/consul-at-datadog/index.html) I found regarding consul monitoring.
It does makes sense

**Comment by jeinwag** [comment]
Unfortunately, these metrics aren't exposed via the Consul HTTP or RPC APIs.

Currently, the only way to get them into Prometheus is using the statsd_exporter.

**Comment by grobie** [comment]
There is a long standing issue for providing all metrics over a HTTP API: https://github.com/hashicorp/consul/issues/817.

At SoundCloud we have a side-car next to every consul agent which queries serf and other stats via the consul ctl / rpc interface and exposes it via Prometheus.

**Comment by EvertMDC** [comment]
Some consistency would indeed be good.
We are currently using the statsd exporter running next to consul.

**Comment by arianvp** [comment]
This has been resolved in https://github.com/hashicorp/consul/pull/3369

More metrics are now exposed through the `HTTP` API

**Comment by Luubosi** [comment]
hi,
will be metrics added from /v1/agent/metrics?
Could you tell me some date?

or if it is possible only with statsd, do you have YAML-based config format of this config
https://gist.github.com/dj-wasabi/d9b31c4b74e561c72512f4edbdfe6927
thanks

**Comment by simonpasquier** [comment]
Recent versions of Consul support the Prometheus exposition natively (see https://www.consul.io/docs/agent/options#telemetry-prometheus_retention_time) so this doesn't need to be reimplemented in the exporter IMHO.
