### ISSUE TITLE
Support client connections to TLS servers

### ISSUE THREAD

**Issue by grobie** [prometheus/consul_exporter#32]
The Consul HTTP API might be secured using TLS, the consul_exporter should support that in order to query for data.

**Comment by soumyadipDe** [comment]
We are planning to use prometheus as our monitoring platform but this issue is being the pain point.

**Comment by deepthawtz** [comment]
I thought we added this support here: https://github.com/prometheus/consul_exporter/commit/05930011f30edc73a5f307893317236deb53ea34

**Comment by deepthawtz** [comment]
I'm currently doing `consul_exporter -consul.server=https://HOSTNAME:443`

**Comment by soumyadipDe** [comment]
Consul can be configured to do client verification using TLS certificates. Is that part covered i.e. can we pass TLS client certificates to consul_exporter that consul can verify?

**Comment by grobie** [comment]
@soumyadipDe not yet, I'll look into porting similar support we already have in other components over.

**Comment by grobie** [comment]
The consul/api package already provides a `SetupTLSConfig()` function we just need to call with the pathes of the certificate files.
