### ISSUE TITLE
Server not reachable

### ISSUE THREAD

**Issue by fabMrc** [prometheus/consul_exporter#34]
Hi

I used the docker image consul_exporter as described in the documentation and i cannot reach the metrics exported by the exporter.
So i used option like web.listen-address (I tried 0.0.0.0, 127.0.0.1...) and path but nothing better.
docker logs in info mode does not trace problem

A curl with http://$IP:9107/metrics respond Connection refused

**Comment by grobie** [comment]
Can you paste the command you executed to start the exporter? What is the output of `netstat -lntp`?

**Comment by fabMrc** [comment]
docker run -d -p 9107:9107 prom/consul-exporter -consul.server=localhost:8500

netstat -netlup 
tcp6       0      0 :::9107                 :::*                    LISTEN      0          37431      4453/docker-proxy
