### ISSUE TITLE
ACL support

### ISSUE THREAD

**Issue by deepthawtz** [prometheus/consul_exporter#39]
once a consul cluster is locked down w/ ACL `consul_exporter` cannot export metrics

I added this to enable support for that and tested:

```diff
diff --git a/consul_exporter.go b/consul_exporter.go
index 77d6790..dae7356 100644
--- a/consul_exporter.go
+++ b/consul_exporter.go
@@ -107,6 +107,7 @@ func NewExporter(uri, kvPrefix, kvFilter string, healthSummary bool, consulTimeo
                Address:    u.Host,
                Scheme:     u.Scheme,
                HttpClient: httpClient,
+               Token:      os.Getenv("CONSUL_TOKEN"),
        })
```

I made `CONSUL_TOKEN` an environment variable so I don't have to expose it in a command

**Comment by grobie** [comment]
@deepthawtz I think this is called `CONSUL_HTTP_TOKEN` in the [consul code base](https://github.com/hashicorp/consul/blob/c744792fc4d665363dba0ecfc7d05fdedc9cab32/api/api.go#L28-L30), right? Any reason not to use the same name?

**Comment by deepthawtz** [comment]
you are correct https://github.com/hashicorp/consul/blob/c744792fc4d665363dba0ecfc7d05fdedc9cab32/api/api.go#L210-L212

merely setting `CONSUL_HTTP_TOKEN` will be enough

**Comment by grobie** [comment]
It actually doesn't work yet as we don't use their DefaultConfig
initializer. I'll send a patch later.
