### ISSUE TITLE
[Question] Proper way to run consul_exporter?

### ISSUE THREAD

**Issue by Ashald** [prometheus/consul_exporter#42]
Is it enough to run `consul_exporter` only on server nodes or there are some metrics that can be extracted only when `consul-exporter` runs on "local agents' and it's better to run it on every host where we have Consul? We're Ok with any of those approaches - just want to understand best way to run it and don't miss metrics.

Thanks!

**Comment by michaelmcguinness** [comment]
I believe it only needs to be run locally to your prometheus service and not on every agent.

**Comment by grobie** [comment]
This is correct, consul_exporter provides information about the registered nodes and services inside a consul datacenter. Therefore you only need one exporter per cluster.

There are plans to provide operational metrics about a consul process itself, but this is blocked on #29 and https://github.com/hashicorp/consul/issues/817.
