### ISSUE TITLE
separate metrics for service health status warning and critical

### ISSUE THREAD

**Issue by nickvth** [prometheus/consul_exporter#44]
Is it possible to split consul_health_service_status into:
- consul_health_service_critical 0 = passing 1 = critical
- consul_health_service_warning 0 = passing  1 = warning
- keep also consul_health_service_status for backward compatibility

When a service check is warning in consul we want a low incident and when critical a high incident

**Comment by brian-brazil** [comment]
You can alert on this without any changes to the exporter.

**Comment by nickvth** [comment]
ok, is that a different value  "consul_health_service_status" : 1 warning and 2 critical?
