### ISSUE TITLE
status for consul_health_service_status metric not available 

### ISSUE THREAD

**Issue by AmandaHassoun** [prometheus/consul_exporter#60]
I don't see the status variable in prometheus: only check, hostclass, instance, job, node, service_id, and service_name.

**Comment by grobie** [comment]
This will be available with the next release.

**Comment by AmandaHassoun** [comment]
Amanda H.

On Jun 18, 2017, at 11:54 AM, Tobias Schmidt <notifications@github.com<mailto:notifications@github.com>> wrote:


This will be available with the next release.

**Comment by AmandaHassoun** [comment]
Do you have an approximate date for this?

**Comment by grobie** [comment]
Not yet, I'd like to get #45 solved.

**Comment by AmandaHassoun** [comment]
Cool! Thanks for getting back to me :)

Amanda H.

On Jun 19, 2017, at 7:33 PM, Tobias Schmidt <notifications@github.com<mailto:notifications@github.com>> wrote:


Not yet, I'd like to get #45<https://github.com/prometheus/consul_exporter/issues/45> solved.
