### ISSUE TITLE
consul_exporter too slow when you have thousands of services

### ISSUE THREAD

**Issue by iksaif** [prometheus/consul_exporter#62]
Looks like consul_exporter is re-fetching all the data each time a client goes on /metrics.

This unfortunately makes it unusable when you have thousands of services and tens of clients pulling from /metrics.

Improvements that could help:
* have an option to fetch the status in the background and keep it cached for some amount of time (while exposing the staleness, of course). I know that people don't like caching collect(), but doing thousands of http queries each time collect() is called isn't really better.
* have an option to export pre-aggregated status per service. Writing the status of tens of thousands of nodes isn't really practical or fast.

cc: @kamaradclimber

**Comment by grobie** [comment]
Who are these clients? I don't think it's common to have "tens of clients pulling /metrics". If your consul_exporter makes thousands of HTTP requests, it sounds like you set `--consul.health-summary`. That's a feature which only works on very small clusters and is off by default for that reason. I strongly recommend disabling it.

**Comment by iksaif** [comment]
I think `--consul.health-summary` is on by default, and that's something that I would like to have exposed to prometheus, even if it's slightly stale (~5min or so). This for example would allow me to know if a service is supposed to be present in this datacenter or not.

I have at least three clients, in order to be N+2, and sometime another team might pull things from the consul_exporter directly (sure, we could gather everything on one promtheus, and then use federation, that just makes the staleness issue worse).

**Comment by iksaif** [comment]
cc: @Thib27, we will see if we can send a PR soon.

**Comment by iksaif** [comment]
The annoying thing is that /v1/internal/ui/services would contain all we need, but clearly we don't want to depend on that.

Another way to do that would be to do something like the blackbox exporter (https://github.com/prometheus/blackbox_exporter/blob/master/main.go#L75) with regexps to filter services (on names or tags) and making sure that the calls are done in parallel on the consul exporter side.

**Comment by grobie** [comment]
Health summaries are fetched in parallel by now https://github.com/prometheus/consul_exporter/pull/68
