### ISSUE TITLE
collected before with the same name and label values

### ISSUE THREAD

**Issue by DiamondYuan** [prometheus/consul_exporter#64]
My Consul have 2 service.
"trading" and "/trading" when i use consul_expoter.
in consul ui label they are different,but service name is same.

An error has occurred during metrics collection:

collected metric consul_catalog_service_node_healthy label:<name:"node" value:"c8092e93a4b1" > label:<name:"service_id" value:"trading" > label:<name:"service_name" value:"trading" > gauge:<value:1 >  was collected before with the same name and label values

**Comment by maxramqvist** [comment]
I have the same issue but only for the commits after tags gets picked up from Consul. Ive tried a couple, including the first with tag-support and the latest from master.

We are running Consul 1.0.6.

`An error has occurred during metrics collection:

27 error(s) occurred:
* collected metric consul_service_tag label:<name:"node" value:"vsp1154" > label:<name:"service_id" value:"docker" > label:<name:"tag" value:"prod" > gauge:<value:1 >  was collected before with the same name and label values
* collected metric consul_service_tag label:<name:"node" value:"vsp13" > label:<name:"service_id" value:"docker" > label:<name:"tag" value:"prod" > gauge:<value:1 >  was collected before with the same name and label values`

We have around 200 services in Consul and would greatly benefit from tag support :)

**Comment by maxramqvist** [comment]
@DiamondYuan did you ever figure it out?

**Comment by DiamondYuan** [comment]
@maxramqvist  Sorry,now we don't use consul。

**Comment by Techcadia** [comment]
I also encountered this issue when I had duplicate tags in my service

```
PS [dev:example:ip-127-0-0-5] C:\ProgramData\consul\config> (irm -UseBasicParsing http://localhost:8500/v1/agent/services).orders.tags
az:b
env:dev
example
example
dev-example
```



```
An error has occurred during metrics collection:

2 error(s) occurred:
* collected metric consul_service_tag label:<name:"node" value:"ip-127-0-0-10.us-east-1.compute.internal" > label:<name:"service_id" value:"example" > label:<name:"tag" value:"example" > gauge:<value:1 >  was collected before with the same name and label values
* collected metric consul_service_tag label:<name:"node" value:"ip-127-0-0-5.us-east-1.compute.internal" > label:<name:"service_id" value:"example" > label:<name:"tag" value:"example" > gauge:<value:1 >  was collected before with the same name and label values
```

**Comment by simonpasquier** [comment]
There are at least 2 issues:
* the list of `tags` can include duplicated values and the exporter should collect them only once.
* a service name with a forward slash is problematic because its health can't be queried (see https://github.com/hashicorp/consul/issues/1096). The exporter needs to skip it.
