### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by joshuaspence** [prometheus/consul_exporter#67]
Version 0.3.0 was released around 6 months ago. Are there any plans to tag a new release?

**Comment by grobie** [comment]
Yes, of course. Unfortunately I don't have too much time right now and will be away next week. I'll try to get it done mid September.

**Comment by joshuaspence** [comment]
bump :)

**Comment by grobie** [comment]
I'll try to get #61 in as well and cut a release afterwards.

**Comment by roman-vynar** [comment]
bump :)

**Comment by rhuddleston** [comment]
bump :)

**Comment by Techcadia** [comment]
Bump???

**Comment by farvour** [comment]
Also, bump.

**Comment by roadrunner** [comment]
bump++

**Comment by gmauleon** [comment]
bump +++ ;)

**Comment by grobie** [comment]
Done https://github.com/prometheus/consul_exporter/releases/tag/v0.4.0
