### ISSUE TITLE
Using exporter to scrape metrics of a remote cluster that uses TLS.

### ISSUE THREAD

**Issue by AlexMussell** [prometheus/consul_exporter#70]
Hey!
As the title states, I am trying to scrape metrics of a remote cluster that uses TLS, where the remote host running the exporter is not a part of the cluster. 
I got as far as running this command (with the cert/keys all under /home/ubuntu/):

./consul_exporter --consul.server="IP:PORT" --consul.ca-file="/home/ubuntu/ca.crt" --consul.cert-file="/home/ubuntu/client.crt" --consul.key-file="/home/ubuntu/client.key"

For the port number I have tried all exposed ports: 8300, 8301, 8302, 8400, 8500, and 53.

For all the ports i receive either a "connection refused" or "connection reset", and I seem to now be at a bit of a dead end. Could you please advise on how I could achieve this?

**Comment by grobie** [comment]
Can't reproduce, please re-open if you still have issues with TLS.
