### ISSUE TITLE
Error Building Binaries

### ISSUE THREAD

**Issue by amang017** [prometheus/consul_exporter#72]
![image](https://user-images.githubusercontent.com/30700440/32246821-4812f78a-be4e-11e7-9b45-1eaf89188b6e.png)

Hi,
I downloaded the consul_exporter to my Unix/Linux machine. However I was not able to build the binaries. Its giving me `make: /src/github.com/prometheus/promu/promu: Command not found` error.
Can anyone please provide detailed/working steps for this in UNIX/Linux and Windows machine?

thanks in advance!

**Comment by grobie** [comment]
Make sure to set the `$GOPATH` environment variable correctly and clone the exporter into `$GOPATH/src/github.com/prometheus/consul_exporter`.
