### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by varundmishra** [prometheus/consul_exporter#76]
Hi,

Can someone please put out an official release with the latest commits?
The last release seems to be outdated.
I would be happy to help if I am given access.

Varun

**Comment by roidelapluie** [comment]
Hi, @grobie what about this?

**Comment by grobie** [comment]
Done https://github.com/prometheus/consul_exporter/releases/tag/v0.4.0

**Comment by varundmishra** [comment]
Thanks @roidelapluie @grobie
