### ISSUE TITLE
Readme needs build dependencies

### ISSUE THREAD

**Issue by davis282** [prometheus/consul_exporter#85]
Readme needs to include build dependencies as it's not as simple as make & run if you don't have the dependencies, which aren't listed.

**Comment by grobie** [comment]
The dependencies are vendored.

**Comment by grobie** [comment]
I can't reproduce the issue on a fresh checkout. As a standard golang project, make sure to clone the project into `$GOPATH/src/github.com/prometheus/consul_exporter`.
