### ISSUE TITLE
Export service_tags metric for untagged services, too?

### ISSUE THREAD

**Issue by jeinwag** [prometheus/consul_exporter#90]
Currently, consul_exporter doesn't provide a service_tags metric for untagged services. 

Maybe it would be better to export a metric with an empty label in such cases, e.g:
```
consul_service_tags{service_id="myservice",service_tags=""}
```
This would make joining and querying easier.

I can implement this but would first like to hear your opinions.

**Comment by brian-brazil** [comment]
That'd imply that there's a tag with an empty value. You probably want to use some other metric that has a service_id label for this purpose.

**Comment by jeinwag** [comment]
@brian-brazil Consul tags are just tags, not labels, so they don't have any values.
The service_tags label includes all tags of a service joined together, separated by comma.

**Comment by brian-brazil** [comment]
It looks like a series per tag to me: https://github.com/prometheus/consul_exporter/blob/master/consul_exporter.go#L312

**Comment by jeinwag** [comment]
You are corrent, so my original suggestion won't work.
