### ISSUE TITLE
Does consul_exporter support consul API environment variables?

### ISSUE THREAD

**Issue by ntgdi** [prometheus/consul_exporter#98]
The documentation for consul_exporter mentions this:

Environment variables

The consul_exporter supports all environment variables provided by the official consul/api package, including CONSUL_HTTP_TOKEN to set the ACL token.

But, I didn't see where the consul_exporter sets any such members in the TLSConfig to indicate InsecureSkipVerify, for example(if CONSUL_HTTP_SSL_VERIFY=false).  Am I misunderstanding how this works?  Also, I tried setting the environment variable for the consul_exporter process, but still get this error:
/v1/status/peers: x509: certificate signed by unknown authority" source="consul_exporter.go:171"

Thanks!

**Comment by ntgdi** [comment]
I mean it appears that the consul_exporter code instantiates a new TLSConfig wherein the InsecureSkipVerify field does not get explicitly set, then calls defaultConfig()(wherein the environment variables are processed), but the TLSConfig that gets used is the one instantiated earlier, not the one that gets set in defaultConfig.  Can anyone please sanity-check that theory?  Thanks!

**Comment by ray1729** [comment]
@ntgdi I agree with your reading of the code. the `TLSConfig` that is created will always have `InsecureSkipVerify == false`. I ran into this problem too so created a PR, #99 ,  to add a command-line flag to set this.  Of course this does not solve the problem of the environment variables but it's a useful work-around.

**Comment by simonpasquier** [comment]
Closing it as I've merged #99 and it should now be possible to disable certificate verification if needed.
